### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by lvzixun** [hqwrong/s5#1]
好巧， socks5这个模块， 我在做hive的时候也写过demo： https://github.com/lvzixun/hive/blob/master/examples/socks5.lua  :D

**Comment by hqwrong** [comment]
@lvzixun 我专门是给telegram写的 telegram的socks5代理支持账号密码认证

**Comment by lvzixun** [comment]
telegram的socks5 跟普通的有什么不一样？

**Comment by hqwrong** [comment]
就是普通的socks5。 socks5协议本身支持账号密码认证，一般soks5服务器没有做，我就自己写了一个
